border_type = "Hidden"
client_id_command = "cat /run/secrets/spot_client_id"
client_port = 8080
cover_img_length = 10
cover_img_scale = 1.9
enable_media_control = true
liked_icon = "󰋑 "
pause_icon = " "
play_icon = " "
progress_bar_type = "Rectangle"
seek_duration_secs = 10
theme = "oxocarbon"

[device]
audio_cache = false
autoplay = true
bitrate = 320
device_type = "speaker"
name = "lain"

[layout]
playback_window_position = "Bottom"
