[[themes]]
name = "oxocarbon"

[themes.component_style.block_title]
fg = "White"
modifiers = ["Italic", "Bold"]

[themes.component_style.current_playing]
fg = "Red"
modifiers = ["Bold"]

[themes.component_style.like]
fg = "BrightBlack"
modifiers = ["Bold"]

[themes.component_style.page_desc]
fg = "White"
modifiers = ["Bold", "Italic"]

[themes.component_style.playback_album]
fg = "BrightCyan"

[themes.component_style.playback_artists]
fg = "BrightCyan"

[themes.component_style.playback_metadata]
fg = "Blue"
modifiers = ["Italic"]

[themes.component_style.playback_track]
fg = "BrightCyan"
modifiers = ["Italic"]

[themes.component_style.playback_progress_bar]
fg = "Red"
modifiers = ["Bold", "Italic"]

[themes.component_style.playlist_desc]
fg = "White"
modifiers = ["Bold", "Italic"]

[themes.component_style.secondary_row]
bg = "BrightBlack"

[themes.component_style.selection]
fg = "Red"
modifiers = ["Reversed"]

[themes.component_style.table_header]
fg = "White"
modifiers = ["Bold", "Italic"]

[themes.component_style.lyrics_played]
fg = "Red"
modifiers = ["Italic"]

[themes.palette]
black = "#121212"
bright_black = "#262626"
blue = "#5fafff"
foreground = "#4e4e4e"
bright_cyan = "#87d7ff"
cyan = "#5fd7d7"
red = "#ff87af"
white = "#e4e4e4"