add_newline = false
format = "${custom.start}$directory${custom.end}$git_branch$git_state$git_status$character"
right_format = "$cmd_duration"
scan_timeout = 10

[custom.start]
command = "echo $PWD"
when = true
format = "\u001b\\]8;;file://$output\u001b\\\\"

[custom.end]
when = true
format = "\u001b\\]8;;\u001b\\\\"

[character]
error_symbol = "[λ](#ff87af)"
success_symbol = "[λ](#ff5f87)"
vimcmd_symbol = "[Λ](#ff5f87)"
vimcmd_replace_one_symbol = "[Λ](#87d7ff)"
vimcmd_visual_symbol = "[Λ](#5faf5f)"

[cmd_duration]
style = "#5fd7d7"

[directory]
style = "#5fafff"

[git_branch]
style = "#ff5f87"

[git_state]
style = "#5faf5f"

[git_status]
style = "#5fafff"
