#!/bin/sh

case $1 in
  ls | list) shift
    nvd list $* ;;
  dl | delete) shift
    nh clean all $* ;;
  up | update) shift
    cd $FLAKE
    nix flake update $* ;;
  sw | switch) shift
    nh os switch $* ;;
  ss | search) shift
    nh search $* ;;
  bt | boot) shift
    nh os boot $*;;
  sr | source) ;;
esac
