#!/bin/sh
mode=$1 && shift
params=$*
case $mode in
  ls | list)
    nvd list $params ;;
  dl | delete)
    nh clean all $params ;;
  up | update)
    cd $FLAKE; nix flake update $params ;;
  sw | switch)
    nh os switch $params ;;
  ss | search)
    nh search $params ;;
  bt | boot)
    nh os boot $params ;;
  sr | source)
    ;;
  *) exit 1 ;;
esac
